# Python

In [1]:
x = [2, 5, 1, 7, 9, 6, 5]

## Reverse the order of elements in the array

In [2]:
x[::-1]

[5, 6, 9, 7, 1, 5, 2]

## Select element greater than 3

In [3]:
[el for el in x if el > 3]

[5, 7, 9, 6, 5]

# How many times each element appears in the list?

In [4]:
{el : x.count(el) for el in set(x)}

{1: 1, 2: 1, 5: 2, 6: 1, 7: 1, 9: 1}

In [5]:
from collections import Counter
Counter(x)

Counter({2: 1, 5: 2, 1: 1, 7: 1, 9: 1, 6: 1})

# Numpy

In [6]:
import numpy as np

In [7]:
a = np.random.randint(low = 0, high = 100, size = 8 )
print(a)

[44 23 38 98 17 24 65  6]


# Q: Sort the elements in the array

In [8]:
np.sort(a)

array([ 6, 17, 23, 24, 38, 44, 65, 98])

# Q: Return the index of the second largest element

In [9]:
np.argsort(a)[-2]

6

In [12]:
a = np.random.choice(np.arange(10), 7, replace = False)
b = np.random.choice(np.arange(10), 7, replace = False)
print(a, b)

[9 4 2 8 7 0 3] [8 4 3 1 9 2 6]


# Q: Find the intersection between the elements of a and b

In [13]:
np.intersect1d(a, b)

array([2, 3, 4, 8, 9])

# Q: Find the difference between the elements of a and b

In [14]:
np.setdiff1d(a, b)

array([0, 7])

# Q: Find the index of the elements in a greater than 5

In [16]:
np.where(a>5)[0]

array([0, 3, 4])

# Matrices

In [17]:
a = np.eye(3)

# Q: What does the following line return?

In [18]:
a.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Q: What is the shape of the object returned by the following?

In [22]:
a = np.arange(9).reshape(-1, 3)

# Q: Select the element on the third column and the second row

In [23]:
a[1, 2]

5

# Select the elements in the second column

In [28]:
a[:, 1]

array([1, 4, 7])

# Q: Sum the elements on each column

In [26]:
a.sum(axis = 1)

array([ 3, 12, 21])

# Pandas

In [30]:
import pandas as pd

In [35]:
df = pd.DataFrame(np.random.randint(1, 10, size = (10, 2)), columns = ['price_per_unit','nb_units'])
df

price_per_unit  nb_units
0               5         4
1               7         3
2               3         2
3               9         8
4               1         9
5               2         4
6               3         8
7               4         3
8               3         9
9               2         6

In [38]:
days = np.random.choice(["Monday", "Tuesday", "Friday"], size = 10)
print(days)

['Friday' 'Tuesday' 'Tuesday' 'Tuesday' 'Friday' 'Monday' 'Tuesday'
 'Monday' 'Tuesday' 'Friday']


In [45]:
players = np.random.choice(["John", "Mary"], size = 10)
print(players)

['Mary' 'Mary' 'John' 'John' 'John' 'John' 'John' 'Mary' 'John' 'John']


# Q: Add the column days to the dataframe

In [46]:
df["day"] = days
df["players"] = players

# Q: compute in a new column the total price of bought units knowing that  on Fridays there is a reduction of 50%

In [44]:
df["price"] = df.apply(lambda x: x["price_per_unit"] * x["nb_units"]
                       if x["day"] != "Friday" else
                       (x["price_per_unit"] * x["nb_units"] / 2),
                       axis=1)

df

price_per_unit  nb_units      day  price
0               5         4   Friday   10.0
1               7         3  Tuesday   21.0
2               3         2  Tuesday    6.0
3               9         8  Tuesday   72.0
4               1         9   Friday    4.5
5               2         4   Monday    8.0
6               3         8  Tuesday   24.0
7               4         3   Monday   12.0
8               3         9  Tuesday   27.0
9               2         6   Friday    6.0

# Q: What day brought the highest revenu?

In [56]:
df.groupby("day")["price"].sum()

day
Friday      20.5
Monday      20.0
Tuesday    150.0
Name: price, dtype: float64

In [58]:
df.groupby("day")["price"].sum().sort_values(ascending = False).index[0]

'Tuesday'

# Q:  How much money did each player spend on each day?

In [62]:
df.groupby(["players", "day"])["price"].sum()

players  day    
John     Friday      10.5
         Monday       8.0
         Tuesday    129.0
Mary     Friday      10.0
         Monday      12.0
         Tuesday     21.0
Name: price, dtype: float64